### ISSUE TITLE
Allow access only to two users or more or only group  

### ISSUE THREAD

**Issue by salim114** [hurik/LdapRecord-Laravel-Example-Project#1]
Hi @hurik 

First of all i want to thank you for your wonderfull Laravel-Example-Project that works like a sharm
it was so inspiring that i made a simple tutorial for that please check it :

https://www.youtube.com/watch?v=ghJC_FJAo20

But now am facing another issue with restricted users or group access, i can allow juste one user by doing this : `LDAP_BASE_DN="uid=gauss,dc=example,dc=com"` (please check picture)

![ldappic](https://user-images.githubusercontent.com/43864609/90313279-34166400-df03-11ea-9b80-cc8f013d02e7.png)

My issues : 
1 - how to do so allowing two or three users only ?
2 - how to allow only one group like (ou=mathematicians) for example ?
3 - do we manage my issues in simply working only with `.env` file ?

Best regards.

**Comment by hurik** [comment]
Hi @salim114 

1 and 2:
What you need is a rule, where you can restrict which user or group can login: https://ldaprecord.com/docs/laravel/auth/configuration/#rules
3:
I don't think it is possible, but I'm not sure.

you should ask such kind of question in the https://github.com/DirectoryTree/LdapRecord-Laravel repository.

Best regards,
Andreas
